package com.example.toaster.network;

public interface NetworkConstants {
    int CACHE_SIZE = 10 * 1024 * 1024; // 10 MB
    int DEFAULT_INITIAL_DELAY = 50;
    int DEFAULT_NUM_RETRIES = 2;
    int DEFAULT_TIME_OUT = 10;
    int DEFAULT_READ_WRITE_TIME_OUT = 45;
    String LOGIN_TOKEN_PREFIX = "Bearer ";

    interface ErrorCode {
        String OTP_INVALID = "OTP_INVALID";
        String MOBILE_NUMBER_EXISTS = "MOBILE_NUMBER_EXISTS";
        String MOBILE_NUMBER_NOT_VERIFIED = "MOBILE_NUMBER_NOT_VERIFIED";
        String CURRENT_PASSWORD_INVALID = "CURRENT_PASSWORD_INVALID";
        String EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";
        String ACCOUNT_LOCKED = "ACCOUNT_LOCKED";
        String INVALID_GENDER = "INVALID_GENDER";
        String MOBILE_NUMBER_INVALID = "MOBILE_NUMBER_INVALID";
        String CUSTOMER_EMAIL_INVALID = "CUSTOMER_EMAIL_INVALID";
        String CUSTOMER_REGISTRATION_EMAIL_CONFIRMATION = "CUSTOMER_REGISTRATION_EMAIL_CONFIRMATION";
        String INVALID_CREDENTIAL = "INVALID_CREDENTIAL";
        String EMAIL_LIMIT_EXCEED = "EMAIL_LIMIT_EXCEED";
        String CUSTOMER_EMAIL_EXISTS = "CUSTOMER_EMAIL_EXISTS";
        String RECORDS_NOT_FOUND = "RECORDS_NOT_FOUND";
        String NOT_AUTHORIZED_TO_SUBMIT_CLAIM = "NOT_AUTHORIZED_TO_SUBMIT_CLAIM";
        String CLAIM_SUBMISSION_EXPIRED = "CLAIM_SUBMISSION_EXPIRED";
        String CLAIM_PROFILE_NO_FOUND = "CLAIM_PROFILE_NO_FOUND";
        String NATIONAL_ID_EXPIRED = "NATIONAL_ID_EXPIRED";
        String NOT_REGISTRATION = "NOT_REGISTRATION";
        String PASSWORD_CHARACTERS_INVALID = "PASSWORD_CHARACTERS_INVALID";
        String TERM_AND_CONDITION_ERROR = "TERM_AND_CONDITION_ERROR";
        String PASSWORD_ALREADY_USED = "PASSWORD_ALREADY_USED";
        String ACTIVE_ORDERS = "ACTIVE_ORDERS";

        String CART_LIMIT_REACHED = "CART_LIMIT_REACHED";
        String QTY_NOT_AVAILABLE = "QTY_NOT_AVAILABLE";
        String MAXIMUM_QTY_REACHED = "MAXIMUM_QTY_REACHED";

        String INVALID_CUSTOMER = "INVALID_CUSTOMER";
        String ORDER_PRICE_LESS_THAN_DIVISOR = "ORDER_PRICE_LESS_THAN_DIVISOR";
        String TOKEN_TRANSFER_SELF_REQUEST = "TOKEN_TRANSFER_SELF_REQUEST";
        String TOKEN_TRANSFER_LIMIT = "TOKEN_TRANSFER_LIMIT";
        String TOKEN_TRANSFER_ERROR = "TOKEN_TRANSFER_ERROR";

        String CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";

        String NOT_ELIGIBLE_AGE = "NOT_ELIGIBLE_AGE";
        String SESSION_EXPIRED = "SESSION_EXPIRED";

        String SERVER_IN_UPGRADE = "SERVER_IN_UPGRADE";
        String REQUEST_PARAMETERS_ERROR = "REQUEST_PARAMETERS_ERROR";
        String MIN_PASSWORD_USE = "MIN_PASSWORD_USE";
        String OTP_LIMIT_EXCEED="OTP_LIMIT_EXCEED";
        String ADD_MORE_SERIES_NOT_ALLOWED = "ADD_MORE_SERIES_NOT_ALLOWED";
        String INVALID_SUBMITTED_NUMBER_SERIES = "INVALID_SUBMITTED_NUMBER_SERIES";
        String INVALID_FAV_SERIES_ALIAS = "INVALID_FAV_SERIES_ALIAS";
        String NO_SECURITY_QUESTION_SAVED = "NO_SECURITY_QUESTION_SAVED";
        String INVALID_DOB = "INVALID_DOB";
        String INVALID_SECURITY_ANSWER = "INVALID_SECURITY_ANSWER";
        String INVALID_ADDRESS_ID = "INVALID_ADDRESS_ID";
        String SOME_ERROR_OCCURED = "SOME_ERROR_OCCURED";
        String ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED";
        String PARSING_ERROR = "PARSE_ERROR";
        String REQUIRED_PARAMETER_FIRSTNAME = "REQUIRED_PARAMETER_FIRSTNAME";
        String REQUIRED_PARAMETER_LASTNAME = "REQUIRED_PARAMETER_LASTNAME";
        String REQUIRED_PARAMETER_POSTCODE = "REQUIRED_PARAMETER_POSTCODE";
        String REQUIRED_PARAMETER_LANDMARK = "REQUIRED_PARAMETER_LANDMARK";
        String REQUIRED_PARAMETER_REGION_NAME = "REQUIRED_PARAMETER_REGION_NAME";
        String REQUIRED_PARAMETER_STREET_1 = "REQUIRED_PARAMETER_STREET_1";
        String REQUIRED_PARAMETER_STREET_2 = "REQUIRED_PARAMETER_STREET_2";
        String REQUIRED_PARAMETER_CITY = "REQUIRED_PARAMETER_CITY";
        String DIFFERENT_FROM_EMAIL = "DIFFERENT_FROM_EMAIL";
        String MAX_PASSWORD_LENGTH = "MAX_PASSWORD_LENGTH";
        String INVALID_RESET_PASSWORD_TOKEN = "INVALID_RESET_PASSWORD_TOKEN";
        String ISD_CODE_INVALID = "ISD_CODE_INVALID";
        String CLAIM_PROFILE_LOCKED = "CLAIM_PROFILE_LOCKED";
        String CLAIM_ALREADY_SUBMITTED = "CLAIM_ALREADY_SUBMITTED";
        String CLAIM_MAX_UPDATE_REQUEST_REACHED = "MAX_CLAIM_UPDATE_REQUEST_REACHED";
        String OTP_ALREADY_SENT = "OTP_ALREADY_SENT";
        String CONTACT_LIMIT_EXCEED = "CONTACT_LIMIT_EXCEED";
        String DOB_MISMATCHED = "DOB_MISMATCHED";
        String INTERNAL_ERROR = "INTERNAL_ERROR";
        String NI_CREATE_ORDER_INVALID = "NI_CREATE_ORDER_INVALID";
        String NI_ACCESS_TOKEN_INVALID = "NI_ACCESS_TOKEN_INVALID";
        String INTERNAL_ORDER_CREATE_ERROR = "INTERNAL_ORDER_CREATE_ERROR";
        String NI_INVALID_ORDER_REF_ID="NI_INVALID_ORDER_REF_ID";
        String INTERNAL_ORDER_UPDATE_ERROR="INTERNAL_ORDER_UPDATE_ERROR";
        String INVALID_SHIPPING_OR_BILLING_ADDRESS="INVALID_SHIPPING_OR_BILLING_ADDRESS";
        String CLAIM_PROFILE_ALREADY_UNLOCKED="CLAIM_PROFILE_ALREADY_UNLOCKED";
        String CLAIM_PROFILE_ALREADY_REQUESTED_FOR_UPDATED ="PROFILE_ALREADY_REQUESTED_FOR_UPDATED";
        String ALREADY_CLAIMED="ALREADY_CLAIMED";
        String SUBMISSION_ALREADY_EXISTS="SUBMISSION_ALREADY_EXISTS";
        String CUSTOMER_COULD_NOT_DELETE="CUSTOMER_COULD_NOT_DELETE";
        String REQUIRED_PARAMETER_GENDER="REQUIRED_PARAMETER_GENDER";
        String SCRATCH_CARD_VALIDITY_INVALID="SCRATCH_CARD_VALIDITY_INVALID";
    }

    interface errorCodes{
        int ERROR_401 = 401;
    }
}
